### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by long123524** [VSainteuf/pastis-benchmark#10]
How to make own time-series dataset for semantic segmentation？ How do you generate datasets that can be used for training from satellite images and corresponding labels

**Comment by VSainteuf** [comment]
Hi @long123524 ,
You can download the Sentinel-2 time series from data platforms such as Google Earth Engine, THEIA, or Copernicus. 
The semantic segmentation annotations for France are obtained from [this link]( https://geoservices.ign.fr/rpg#telechargementrpg2020).
The annotations are usually in vector format, so you have to rasterise them to obtain pixel level semantic labels.
Cheers.

**Comment by long123524** [comment]
Thanks for your reply. I want to know about that how is the .npy data obtained? What has been done? Are you convenient to provide a code?

**Comment by VSainteuf** [comment]
I don't have a cleaned piece of code for that part, but it is quite straightforward.
The process is as follows:
- Unzip the band files. 
- Upsample all bands to 10m per pixel resolution with bilinear interpolation.
- Stack channels together into a single image.
- Stack different observations together into a time series of images. 
- Store the resulting 4-dimensional array into a numpy file. 

We do not use cloud gap filling.

**Comment by long123524** [comment]
Thanks for your rapid reply. I can do these, but I can not get the 'metadata.geojson' file. How do you get it?

**Comment by long123524** [comment]
Thanks for your rapid reply. I can do these, but I can not produce the 'metadata.geojson' file like PASTIS dataset for our experiments. How do you produce it?

**Comment by VSainteuf** [comment]
The main role of the `metadata.geojson` file is to store the observation dates of each time series. 
So can construct it like this :
```
{
patch_id:
    {
      geometry: patch geo-referenced polygon,
      dates-S2: list of observation dates (YYYY-MM-DD format) for that patch,
      Fold: Fold this patch belongs to.
    }
}
```

**Comment by Yiwei0324** [comment]
What are the name of the bands of the Sentinel_2 time series?And what is the order?

**Comment by vvuonghn** [comment]
Hi @VSainteuf 
Thank you for your work. I have a concern about dataset.
For the satellite data, you got from sentinel 2 from20180924 to 20191019. But ground truth from [this link](https://geoservices.ign.fr/rpg#telechargementrpg2020). 
maybe the crop type change during this period at the same farm
