### ISSUE TITLE
Select Mono_date not work

### ISSUE THREAD

**Issue by ron8520** [VSainteuf/pastis-benchmark#14]
Hi, I want only to select the particular date of images rather than a series. By setting attribute mono_date = "2018-09-02" on PASTIS_Dataset(). It raises 

`Unsupported operand types(s) for -: 'dict' and 'int'` error

**Comment by VSainteuf** [comment]
Hi @ron8520 ,
Thanks for pointing this out, I think I know what the problem is, let me get back to you shortly.

**Comment by VSainteuf** [comment]
Hey, I fixed the problem and also pushed the fix to the utae-paps repository. 
Can you confirm it works for you too now ?
