### ISSUE TITLE
New entry to semantic segmentation leaderboard - TSViT

### ISSUE THREAD

**Issue by michaeltrs** [VSainteuf/pastis-benchmark#20]
Please consider our model TSViT for the PASTIS semantic segmentation leaderboard. You can find a [preprint of our work](https://arxiv.org/pdf/2301.04944.pdf) and [code repo](https://github.com/michaeltrs/DeepSatModels). Further information can be found [here](https://github.com/michaeltrs/DeepSatModels/blob/main/README_TSVIT.md) including link to download trained models.  Overall we achieved OA=83.4, mIoU=65.4 on the five folds of PASTIS.

**Comment by VSainteuf** [comment]
Hi @michaeltrs, could you also share the number of parameters of TSViT ?

**Comment by michaeltrs** [comment]
Hi @VSainteuf, thank you for a prompt response. The model we used in these experiments has 1.657M params.
