### ISSUE TITLE
The Co ordinate reference system(CRS) for the labels  and image patches

### ISSUE THREAD

**Issue by v3nkyc0d3z** [VSainteuf/pastis-benchmark#21]
Thank you for open-sourcing the dataset. I am currently working on a deep learning based harmonization/super-resolution pipeline for Landsat-8 and Sentinel-2 images. I would like to use the annotations from PASTIS dataset to benchmark the performance of the segmentation models when i use a combined time series of Landsat-8 and Sentinel-2 images. It would be very helpful if you can provide me with the information on the Co Ordinate Reference System(CRS) of the annotations and the image patches or some scripts which you used to prepare the dataset. The CRS information is very critical for my work, since it also involves spatial co-registration of the images between both the sources.

Also, the Sentinel-2 patches in the dataset, are they the DN values?

**Comment by VSainteuf** [comment]
Hi @v3nkyc0d3z,
The CRS info is in the metadata.geojson file of the dataset.

What do you mean by DN values ?

**Comment by VSainteuf** [comment]
Ok the pixel values of the numpy files are in the default range of the L2A product (no normalisation).
