### ISSUE TITLE
Numpy Contents

### ISSUE THREAD

**Issue by TolgaBkm** [VSainteuf/pastis-benchmark#25]
Hello and thank you for the dataset.
I'm trying to figure out the contec-nts of the numpy files and they contain 43 images as shown:
![Images](https://github.com/VSainteuf/pastis-benchmark/assets/57003251/4c368ba1-cbf8-4ddc-9499-fb4f150acf04)
I know that each time serie contains 10 bands of Sentinel-2. So assuming that this numpy file contains 4 dates, I should have ended up with 40 files? I cant seem to figure out what the other 3 files are.
Would you kindly elaborate the contents of the numpy's?

**Comment by VSainteuf** [comment]
Hi @TolgaBkm,
each numpy file contains one full image time series for one patch. 
So each numpy file contains a TxCxHxW array where:
- T is the number of dates
- C is the channel dimension (10)
- H and W the spatial dimensions (128)

**Comment by TolgaBkm** [comment]
Thanks for the answer!
