### ISSUE TITLE
Training

### ISSUE THREAD

**Issue by long123524** [VSainteuf/pastis-benchmark#5]
Great job. But I have a question about the dataset. How did .npy formed? How can I use my own dataset for model training?

**Comment by VSainteuf** [comment]
Thanks!
The .npy files are obtained from the Sentinel-2 tiles we downloaded from THEIA, and we use the French Land Parcel Identification System for the annotations. 
You can have a look at `pastis-benchmark/documentation/pastis-documentation.pdf` for more details on the different steps.
